[package]
name = "px"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
