[values]
x = 12
y = "xx"
z = false

[cmds.echo]
matrix = [["a", "b", "c"], [1, 3]]
args = ["${x}", "${#.0}-${#.1}.${z}"]

[cmds.ls]
dir = "./src"

[cmds.install]
values = { dest = "~/go/bin" }
prog = "pwsh"
args = ["-c", "cargo build -r && cp ./target/release/px.exe ${dest}/px.exe"]

[cmds.py]
prog = "python"

[cmds.loopecho]
prog = "pwsh"
args = ["-c", """for ($i = 1; $i -le 100; $i++) { 
    sleep 1
    $cpid = [System.Diagnostics.Process]::GetCurrentProcess().ID
    echo "Pid: $cpid" 
}"""]
