[values]
x = 12
y = "xx"
z = false

[cmds.echo]
matrix = [["a", "b", "c"], [1, 3]]
args = ["${x}", "${#.0}-${#.1}.${z}"]

[cmds.ls]
dir = "./src"

[cmds.install]
values = { dest = "~/go/bin" }
prog = "pwsh"
args = ["-c", "cargo build -r && cp ./target/release/px.exe ${dest}/px.exe"]
