on:
  release:
    types: [created]

jobs:
  release_without_not_required:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          [
            x86_64-unknown-linux-musl,
            x86_64-pc-windows-gnu,
            # x86_64-apple-darwin,
          ]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        with:
          TOOLCHAIN_VERSION: 1.81.0
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
      - name: Checkout output
        run: ls -laR
