on:
  release:
    types: [created]

jobs:
  release_without_not_required:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      
      - name: CompileLinux
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: 1.81.0
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload Linux
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            target/x86_64-unknown-linux-musl/release/px

      - name: CompileWindows
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: 1.81.0
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            target/x86_64-pc-windows-gnu/release/px.exe
